### ISSUE TITLE
Update Rust edition from 2021 to 2024 in Cargo.toml

### ISSUE THREAD

**Issue by zmrdltl** [zmrdltl/rust-leetcode#50]
## Description
We should update our project to use the latest Rust 2024 edition to benefit from new language features and improvements.

## Current behavior
Currently, our project is configured to use Rust 2021 edition as specified in Cargo.toml:
```toml
[package]
# other fields...
edition = "2021"
```

## Expected behavior
Update the Cargo.toml to use Rust 2024 edition:
```toml
[package]
# other fields...
edition = "2024"
```

## Benefits
- Access to latest Rust language features and improvements
- Stay current with Rust ecosystem development
- Potential performance improvements and additional compiler optimizations

## Implementation notes
- Simple change in Cargo.toml
